requirejs.config({
    baseUrl: '../src/js/frontend/',
    paths: {
        // libraries
        jQuery: 'libs/jquery.min',
        ace: 'libs/ace/ace',
        charts: 'libs/charts.min',
        cropper: 'libs/cropper.min',
        moment: 'libs/moment.min',
        progress: 'libs/progressbar.min',
        signature: 'libs/signature.min',
        particle: 'libs/particles.min',
        geocomplete: 'libs/geocomplete',
        owl: 'libs/owl',
        // cryptoJS
        AES: 'libs/cryptoJS/aes',
        MD5: 'libs/cryptoJS/md5',
        // controller
        app: 'controller/app',
        // core
        api: 'controller/core/api',
        cart: 'controller/core/cart',
        db: 'controller/core/db',
        editor: 'controller/core/editor',
        storage: 'controller/core/storage',
        user: 'controller/core/user',
        // default
        main: 'main',
        // pages
        page: 'controller/pages/page',
        about: 'controller/pages/about',
        blog: 'controller/pages/blog',
        course: 'controller/pages/course',
        courses: 'controller/pages/courses',
        eduide: 'controller/pages/eduide',
        home: 'controller/pages/home',
        signup: 'controller/pages/signup',
        // ajax
        ajaxLogin: 'ajax/user/login',
        ajaxRegister: 'ajax/user/register'
    }
});